apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hltaw0f2q-dotnet-basic
  janus-idp.io/tekton: hltaw0f2q-dotnet-basic
  backstage.io/kubernetes-id: hltaw0f2q-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hltaw0f2q-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
